#!/usr/bin/env python3
"""Plan triage: scan docs/superpowers/plans/, upsert tracker issue, auto-delete shipped plans.

Run by the `plan-triage` job in `.github/workflows/cron.yml`, weekly and via workflow_dispatch.

Inputs (env):
  GH_TOKEN          — gh CLI auth (workflow secret)
  GITHUB_REPOSITORY — owner/repo (set by Actions)
  GITHUB_RUN_ID     — run id (set by Actions, for digest footer)

Behavior:
  1. Parse every `docs/superpowers/plans/*.md` for status frontmatter, linked PR refs,
     checkbox counts, first/last commit dates.
  2. Build a markdown digest table.
  3. Find existing tracker issue by HTML-comment marker; edit body, or create new.
  4. For each plan with `status: shipped` AND all linked PRs merged, open a delete-PR.
     Skip if a matching branch / PR already exists.

Convention:
  - Plans grow frontmatter `status: shipped|active|abandoned`.
  - Body references linked PRs as `#NNN`.
"""
from __future__ import annotations

import glob
import json
import os
import re
import subprocess
import sys
from pathlib import Path

import yaml

MARKER = "<!-- engram-plan-triage -->"
PLANS_GLOB = "docs/superpowers/plans/*.md"


def sh(cmd: list[str], check: bool = True, capture: bool = True) -> subprocess.CompletedProcess[str]:
    r = subprocess.run(cmd, check=False, capture_output=capture, text=True)
    if check and r.returncode != 0:
        # Don't raise CalledProcessError: it dumps the whole argv (a multi-KB issue
        # body) and drops stderr, which is the only part that says WHY gh failed.
        sys.exit(f"$ {' '.join(cmd[:3])} … → exit {r.returncode}\n{(r.stderr or '').strip()}")
    return r


def parse_plan(path: str) -> dict:
    text = Path(path).read_text()
    fm: dict = {}
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if m:
        try:
            fm = yaml.safe_load(m.group(1)) or {}
        except yaml.YAMLError:
            fm = {}
    # Authoritative source: frontmatter `linked_prs: [N, N, ...]`. Fall back to
    # body-regex extraction if absent (noisier — picks up cross-repo refs that
    # this workflow can't resolve via `gh pr view` on the current repo).
    fm_prs = fm.get("linked_prs")
    if isinstance(fm_prs, list):
        pr_refs = sorted({int(n) for n in fm_prs if isinstance(n, int)})
    else:
        pr_refs = sorted({int(n) for n in re.findall(r"(?<![A-Za-z0-9/])#(\d+)", text)})
    unchecked = len(re.findall(r"^- \[ \]", text, re.MULTILINE))
    checked = len(re.findall(r"^- \[x\]", text, re.MULTILINE))
    first = sh(["git", "log", "--diff-filter=A", "--follow", "--format=%cs", "--", path]).stdout.strip().split("\n")[-1] or "—"
    last = sh(["git", "log", "-1", "--format=%cs", "--", path]).stdout.strip() or "—"
    return {
        "path": path,
        "status": fm.get("status", "—"),
        "linked_prs": pr_refs,
        "unchecked": unchecked,
        "checked": checked,
        "first": first,
        "last": last,
    }


def pr_merged(num: int) -> bool | None:
    r = sh(["gh", "pr", "view", str(num), "--json", "state"], check=False)
    if r.returncode != 0:
        return None
    try:
        return json.loads(r.stdout).get("state") == "MERGED"
    except json.JSONDecodeError:
        return None


def build_digest(rows: list[dict]) -> str:
    run_id = os.environ.get("GITHUB_RUN_ID", "local")
    table = [
        "| Plan | Status | Checks | First | Last touched | Linked PRs |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        prs = " ".join(f"#{n}" for n in r["linked_prs"]) or "—"
        total = r["checked"] + r["unchecked"]
        checks = f"{r['checked']}/{total}" if total else "—"
        table.append(f"| `{r['path']}` | {r['status']} | {checks} | {r['first']} | {r['last']} | {prs} |")
    return "\n".join(
        [
            MARKER,
            "## Plan triage queue",
            "",
            "Auto-generated by the `plan-triage` job in `.github/workflows/cron.yml`. Surfaces every plan in `docs/superpowers/plans/` with stats so we can spot shipped, abandoned, or stale plans.",
            "",
            f"_Last updated by run {run_id}._",
            "",
            *table,
            "",
            "**Convention** (workflow consumes these):",
            "- Add `status: shipped | active | abandoned` to plan frontmatter when work completes.",
            "- Reference linked PRs in body as `#NNN`.",
            "- When `status: shipped` AND all linked PRs are merged, the next workflow run opens a delete-PR for the plan file.",
        ]
    )


def upsert_tracker(body: str) -> None:
    # Find existing tracker by marker in body.
    repo = os.environ["GITHUB_REPOSITORY"]
    r = sh(
        [
            "gh",
            "search",
            "issues",
            f"repo:{repo}",
            "in:body",
            "engram-plan-triage",
            "state:open",
            "--json",
            "number,body",
            "--limit",
            "10",
        ],
        check=False,
    )
    existing = []
    if r.returncode == 0:
        try:
            existing = [i for i in json.loads(r.stdout) if MARKER in i.get("body", "")]
        except json.JSONDecodeError:
            existing = []
    if existing:
        num = existing[0]["number"]
        sh(["gh", "issue", "edit", str(num), "--body", body])
        print(f"Updated tracker issue #{num}")
    else:
        out = sh(
            [
                "gh",
                "issue",
                "create",
                "--title",
                "[runbook] Plan triage queue",
                "--label",
                "runbook",
                "--body",
                body,
            ]
        )
        print(out.stdout.strip())


def open_delete_pr(plan: dict) -> None:
    slug = Path(plan["path"]).stem
    branch = f"chore/delete-shipped-plan-{slug}"
    # Skip if a PR already exists on this branch.
    pr_check = sh(["gh", "pr", "list", "--head", branch, "--json", "number"], check=False)
    if pr_check.returncode == 0:
        try:
            if json.loads(pr_check.stdout):
                print(f"Skip {plan['path']}: PR already open on {branch}")
                return
        except json.JSONDecodeError:
            pass
    pr_list = " ".join(f"#{n}" for n in plan["linked_prs"])
    sh(["git", "checkout", "-b", branch])
    sh(["git", "rm", plan["path"]])
    sh(
        [
            "git",
            "commit",
            "-m",
            f"chore: delete shipped plan {slug}\n\nAuto-generated by plan-triage workflow.\nPlan marked status:shipped and linked PRs ({pr_list}) are merged.",
        ]
    )
    # ponytail: this push has never run — no plan carries `status:` frontmatter yet, so
    # nothing reaches here. The push itself is fine despite the runner VMs' LAN git-cache
    # `insteadOf`: `git push origin` from these runners is proven daily by verify.yml's
    # ledger-append (ci-ledger) and release-please's release-v* tag push, both on
    # self-hosted isolated runners.
    # What WILL bite is the merge — the commit above is unsigned and main requires signed
    # commits, so the delete-PR opens but cannot be merged. Sign it when a plan first goes
    # `status: shipped` and this path can actually be exercised.
    sh(["git", "push", "-u", "origin", branch])
    sh(
        [
            "gh",
            "pr",
            "create",
            "--base",
            "main",
            "--head",
            branch,
            "--title",
            f"chore: delete shipped plan {slug}",
            "--body",
            f"Auto-generated by the `plan-triage` job in `.github/workflows/cron.yml`.\n\nPlan `{plan['path']}` is `status: shipped` and linked PRs {pr_list} are merged. Safe to delete; git log retains the archive.",
        ]
    )
    sh(["git", "checkout", "main"])
    print(f"Opened delete-PR for {plan['path']}")


def main() -> int:
    plans = sorted(glob.glob(PLANS_GLOB))
    if not plans:
        print(f"No plans found at {PLANS_GLOB}; nothing to triage.")
        return 0
    rows = [parse_plan(p) for p in plans]
    body = build_digest(rows)
    upsert_tracker(body)

    for r in rows:
        if r["status"] != "shipped":
            continue
        if not r["linked_prs"]:
            continue
        merged = [pr_merged(n) for n in r["linked_prs"]]
        if all(m is True for m in merged):
            open_delete_pr(r)
        else:
            unresolved = [n for n, m in zip(r["linked_prs"], merged) if m is not True]
            print(f"Plan {r['path']}: status:shipped but PRs {unresolved} not all merged; skipping delete-PR.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
