Mox.defmock(Engram.AwsKmsMock, for: Engram.AwsKms)
Mox.defmock(Engram.MockEmbedder, for: Engram.Embedder)
Mox.defmock(Engram.MockReranker, for: Engram.Reranker)
Mox.defmock(Engram.MockStorage, for: Engram.Storage)
Mox.defmock(Engram.Paddle.ClientMock, for: Engram.Paddle.Client)
Mox.defmock(Engram.Auth.Clerk.ApiMock, for: Engram.Auth.Clerk.Api)
Mox.defmock(Engram.Email.ProviderMock, for: Engram.Email.Provider)
Mox.defmock(Engram.ObanFacadeMock, for: Engram.ObanFacade)
