defmodule Mix.Tasks.Engram.BackfillOnboardingActions do
  @shortdoc "Backfill onboarding_actions for legacy users with vaults"

  @moduledoc """
  One-shot: insert `first_vault_created` for every user with at least one
  vault. Idempotent via the unique index on (user_id, action).

  Run after deploying the onboarding_actions table:

      mix engram.backfill_onboarding_actions          # dev/test
      bin/engram eval 'Mix.Tasks.Engram.BackfillOnboardingActions.run([])'   # release

  The bigserial `id` column is auto-generated by Postgres and intentionally
  omitted from the INSERT column list; `metadata` defaults to `{}::jsonb`
  via the table default.
  """

  use Mix.Task

  alias Engram.Repo

  @impl Mix.Task
  def run(_args) do
    Mix.Task.run("app.start")

    now = DateTime.utc_now()

    %{num_rows: count} =
      Repo.query!(
        """
        INSERT INTO onboarding_actions (user_id, action, metadata, inserted_at)
        SELECT DISTINCT v.user_id, 'first_vault_created', '{}'::jsonb, $1::timestamptz
        FROM vaults v
        ON CONFLICT (user_id, action) DO NOTHING
        """,
        [now]
      )

    Mix.shell().info("Backfilled #{count} onboarding_actions rows")
    :ok
  end
end
