defmodule Engram.Repo.Migrations.CreateInstanceSettings do
  use Ecto.Migration

  def change do
    create table(:instance_settings, primary_key: false) do
      add :id, :bigint, primary_key: true
      add :registration_mode, :text, null: false, default: "invite_only"
      add :inserted_at, :timestamptz, null: false, default: fragment("now()")
      add :updated_at, :timestamptz, null: false, default: fragment("now()")
    end

    # squawk prefer-identity: Ecto has no built-in IDENTITY macro; add post-create.
    execute(
      "ALTER TABLE instance_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY",
      "ALTER TABLE instance_settings ALTER COLUMN id DROP IDENTITY IF EXISTS"
    )

    # Singleton guard: only id=1 may ever exist. Added NOT VALID (no table
    # scan, brief lock) then VALIDATE separately — squawk constraint-missing-
    # not-valid. Table is empty here, so the validate is also effectively free,
    # but the pattern matches how online-safe constraints are added repo-wide
    # (see 20260528000000_add_family_id_to_device_refresh_tokens.exs).
    execute(
      "ALTER TABLE instance_settings ADD CONSTRAINT singleton CHECK (id = 1) NOT VALID",
      "ALTER TABLE instance_settings DROP CONSTRAINT singleton"
    )

    execute(
      "ALTER TABLE instance_settings VALIDATE CONSTRAINT singleton",
      ""
    )
  end
end
