defmodule Engram.Repo.Migrations.CreateInstanceSettings do
  use Ecto.Migration

  def change do
    create table(:instance_settings, primary_key: false) do
      add :id, :bigint, primary_key: true
      add :registration_mode, :text, null: false, default: "invite_only"
      add :inserted_at, :timestamptz, null: false, default: fragment("now()")
      add :updated_at, :timestamptz, null: false, default: fragment("now()")
    end

    # squawk prefer-identity: Ecto has no built-in IDENTITY macro; add post-create.
    execute(
      "ALTER TABLE instance_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY",
      "ALTER TABLE instance_settings ALTER COLUMN id DROP IDENTITY IF EXISTS"
    )

    # Singleton guard: only id=1 may ever exist.
    create constraint(:instance_settings, :singleton, check: "id = 1")
  end
end
