defmodule Engram.Repo.Migrations.DropFounderGrandfatherColumnsFromUsers do
  use Ecto.Migration

  # Pricing v3 reanchor (2026-05-31). The founder/OG-grandfather machinery
  # (Engram.Billing.FounderCodes + send_og_grandfather_* mailers + the email
  # broadcast Mix task) was ripped along with the rest of the founding-member
  # framing. OG-waitlist is now handled via per-person Paddle discount codes
  # generated by hand in the dashboard.
  #
  # Prod probe 2026-05-31 (FastRaid engram-saas-postgres): 3326 users, 0
  # non-null on either column. Drop is non-destructive at probe time.
  #
  # Uses raw `execute/1` with the `-- squawk-ignore-file` pragma because
  # the lint script (priv/repo/lint_migrations.sh) runs squawk against the
  # rendered DDL — Ecto's `remove/2` form yields
  # `ALTER TABLE users DROP COLUMN ...` which trips `ban-drop-column`. The
  # drop is intentional and verified safe (zero non-null rows in prod) so
  # the ignore is correct here, not policy weakening.
  #
  # squawk's per-rule-inline ignore (`-- squawk-ignore-next-statement`) is
  # NOT a recognized pragma in v2.54 — only `-- squawk-ignore-file` is.
  # That pragma silences squawk for the whole rendered file, which is fine
  # here because lint_migrations.sh only renders migrations newer than
  # origin/main, and this PR ships exactly one migration.
  def up do
    execute """
    -- squawk-ignore-file
    ALTER TABLE users
      DROP COLUMN founder_code_redeemed_at,
      DROP COLUMN og_grandfather_redeemed_at
    """
  end

  def down do
    alter table(:users) do
      add :founder_code_redeemed_at, :utc_datetime_usec
      add :og_grandfather_redeemed_at, :utc_datetime_usec
    end
  end
end
