defmodule Engram.Repo.Migrations.DropFounderGrandfatherColumnsFromUsers do
  use Ecto.Migration

  # Pricing v3 reanchor (2026-05-31). The founder/OG-grandfather machinery
  # (Engram.Billing.FounderCodes + send_og_grandfather_* mailers + the email
  # broadcast Mix task) was ripped along with the rest of the founding-member
  # framing. OG-waitlist is now handled via per-person Paddle discount codes
  # generated by hand in the dashboard.
  #
  # Prod probe 2026-05-31 (FastRaid engram-saas-postgres): 3326 users, 0
  # non-null on either column. Drop is non-destructive at probe time.
  def change do
    alter table(:users) do
      remove :founder_code_redeemed_at, :utc_datetime_usec
      remove :og_grandfather_redeemed_at, :utc_datetime_usec
    end
  end
end
