defmodule Engram.Repo.Migrations.CreatePasswordResetTokens do
  use Ecto.Migration

  # See comment in 20260528000002_create_invites.exs — same pattern.
  @disable_ddl_transaction true
  @disable_migration_lock true

  def change do
    create table(:password_reset_tokens, primary_key: false) do
      add :id, :bigint, primary_key: true
      add :user_id, references(:users, on_delete: :delete_all), null: false
      add :token_hash, :text, null: false
      add :expires_at, :timestamptz, null: false
      add :used_at, :timestamptz
      add :created_by, references(:users, on_delete: :nilify_all)
      add :inserted_at, :timestamptz, null: false, default: fragment("now()")
    end

    execute(
      "ALTER TABLE password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY",
      "ALTER TABLE password_reset_tokens ALTER COLUMN id DROP IDENTITY IF EXISTS"
    )

    create unique_index(:password_reset_tokens, [:token_hash], concurrently: true)
    create index(:password_reset_tokens, [:user_id], concurrently: true)
  end
end
