defmodule Engram.Repo.Migrations.CreateInvites do
  use Ecto.Migration

  # CREATE INDEX CONCURRENTLY can't run in a transaction (squawk
  # require-concurrent-index-creation). CREATE TABLE + ALTER TABLE in the
  # same migration run as their own implicit statements without an outer
  # transaction — fresh table, no contention.
  @disable_ddl_transaction true
  @disable_migration_lock true

  def change do
    create table(:invites, primary_key: false) do
      add :id, :bigint, primary_key: true
      add :token_hash, :text, null: false
      add :created_by, references(:users, on_delete: :delete_all), null: false
      add :label, :text
      add :max_uses, :bigint, null: false, default: 1
      add :use_count, :bigint, null: false, default: 0
      add :expires_at, :timestamptz
      add :revoked_at, :timestamptz
      add :inserted_at, :timestamptz, null: false, default: fragment("now()")
      add :updated_at, :timestamptz, null: false, default: fragment("now()")
    end

    execute(
      "ALTER TABLE invites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY",
      "ALTER TABLE invites ALTER COLUMN id DROP IDENTITY IF EXISTS"
    )

    create unique_index(:invites, [:token_hash], concurrently: true)
    create index(:invites, [:created_by], concurrently: true)
  end
end
