defmodule Engram.Auth.TokenResolver do
  @moduledoc """
  Shared token→user resolution used by both the Auth plug and UserSocket.

  Handles three auth methods in order:
    1. API key  — `engram_` prefix (always available)
    2. Auth provider JWT — delegates to the configured provider (Clerk RS256 or local HS256)
    3. Internal JWT — HS256 tokens from the device flow (always checked as fallback)

  Returns `{:ok, %User{}}` or `{:error, reason}`.
  """

  alias Engram.Accounts

  @spec resolve(any()) ::
          {:ok, Accounts.User.t()}
          | {:ok, Accounts.User.t(), Accounts.ApiKey.t()}
          | {:ok, Accounts.User.t(), :internal_jwt}
          | {:error, atom() | keyword()}

  def resolve("engram_" <> _ = raw_key) do
    case Accounts.validate_api_key(raw_key) do
      {:ok, user, api_key} -> {:ok, user, api_key}
      {:error, _} = err -> err
    end
  end

  def resolve(token) when is_binary(token) do
    case Engram.Auth.provider().verify_token(token) do
      {:ok, %{external_id: ext_id, email: email}} ->
        Engram.Auth.provider().resolve_user(ext_id, email)

      {:error, reason} ->
        if conclusive?(reason) do
          {:error, reason}
        else
          # Token not recognized by provider — try internal HS256 JWT
          # (device flow access tokens generated by Accounts.generate_jwt/1).
          authenticate_internal_jwt(token)
        end
    end
  end

  def resolve(_), do: {:error, :invalid_token}

  # Whether the provider's verdict is final, i.e. retrying the token as an
  # internal HS256 JWT can only fail — and would REPLACE this reason with that
  # verifier's `:signature_error`.
  #
  # That mislabel is why this exists. Originally only `:missing_claims` and
  # `:invalid_signature` stopped here, so an expired Clerk token fell through,
  # failed HS256 (of course — it is RS256), and got logged `signature_error`.
  # Prod carried 6753 of those from three users, pointing an investigation at
  # key rotation when the tokens were simply expired.
  #
  # INVERTED ON PURPOSE: conclusive by DEFAULT, with an explicit list of the
  # only errors meaning "this was never a provider token, go try the internal
  # verifier". The previous version enumerated the conclusive side instead,
  # copying JokenJwks' atoms out of the dep's source — which made the default
  # for anything unrecognised "fall through and get relabelled", the very bug
  # this function fixes. A joken_jwks bump adding or renaming one atom would
  # have restored it silently, with nothing failing. Enumerating the
  # fallthrough means an unknown future atom surfaces under its own name.
  # Wrong-but-visible beats laundered.
  #
  # Why exactly these two:
  #
  #   * `:no_kid_in_token_header` — `JokenJwks.before_verify/2` extracts the kid
  #     BEFORE looking up a signer, and internal tokens (`Engram.Token`) are
  #     signed with no kid at all. This IS the device-flow / OAuth / MCP path,
  #     and `test/engram/auth/token_resolver_test.exs` pins it.
  #   * `:invalid_token` — the parse-failure rescue in
  #     `ClerkToken.verify_clerk_jwt/1`; a string that is not a JWT at all.
  #
  # Everything else reports as itself: claim failures and `:invalid_azp` (both
  # only reachable AFTER the signature verified, since Joken verifies before it
  # validates), and every JokenJwks failure including a signing-key rotation
  # (`:kid_does_not_match`) — the one scenario the 6753-line incident was
  # misdiagnosed as, which until now would itself have logged `signature_error`.
  # `Engram.PromEx.Reliability` documents `could_not_reach_jwks_url` as an
  # expected `reason` tag; before this it could never be emitted.
  #
  # Self-host is unaffected: `Providers.Local.verify_token` and
  # `Accounts.verify_jwt` both bottom out in `Engram.Token.verify_and_validate`,
  # so the old fallthrough ran the identical verifier twice for an identical
  # error. Only the Clerk path's label moves.
  @fall_through_to_internal_jwt [:no_kid_in_token_header, :invalid_token]

  defp conclusive?(reason) when is_atom(reason),
    do: reason not in @fall_through_to_internal_jwt

  # Joken claim-validation failures arrive as a keyword list.
  defp conclusive?(_reason), do: true

  defp authenticate_internal_jwt(token) do
    case Accounts.verify_jwt(token) do
      {:ok, %{"user_id" => user_id}} when is_binary(user_id) ->
        case Accounts.get_user(user_id) do
          # `:internal_jwt` marker distinguishes device-flow / OAuth /
          # MCP access tokens (all minted via Accounts.generate_jwt) from
          # Clerk-authed web-SPA tokens, so cap plugs can tell programmatic
          # ("external tooling") traffic apart from the user in the app.
          %Accounts.User{} = user -> {:ok, user, :internal_jwt}
          _ -> {:error, :user_not_found}
        end

      {:ok, _claims} ->
        {:error, :missing_claims}

      {:error, reason} ->
        # Preserve Joken's structured failure (e.g. [claim: "exp", ...]) so the
        # auth plug can log *why* the token was rejected.
        {:error, reason}
    end
  end
end
