defmodule Engram.Auth.TokenResolver do
  @moduledoc """
  Shared token→user resolution used by both the Auth plug and UserSocket.

  Handles three auth methods in order:
    1. API key  — `engram_` prefix (always available)
    2. Auth provider JWT — delegates to the configured provider (Clerk RS256 or local HS256)
    3. Internal JWT — HS256 tokens from the device flow (always checked as fallback)

  Returns `{:ok, %User{}}` or `{:error, reason}`.
  """

  alias Engram.Accounts

  @spec resolve(any()) ::
          {:ok, Accounts.User.t()}
          | {:ok, Accounts.User.t(), Accounts.ApiKey.t()}
          | {:ok, Accounts.User.t(), :internal_jwt}
          | {:error, atom() | keyword()}

  def resolve("engram_" <> _ = raw_key) do
    case Accounts.validate_api_key(raw_key) do
      {:ok, user, api_key} -> {:ok, user, api_key}
      {:error, _} = err -> err
    end
  end

  def resolve(token) when is_binary(token) do
    case Engram.Auth.provider().verify_token(token) do
      {:ok, %{external_id: ext_id, email: email}} ->
        Engram.Auth.provider().resolve_user(ext_id, email)

      {:error, reason} ->
        if conclusive?(reason) do
          {:error, reason}
        else
          # Token not recognized by provider — try internal HS256 JWT
          # (device flow access tokens generated by Accounts.generate_jwt/1).
          authenticate_internal_jwt(token)
        end
    end
  end

  def resolve(_), do: {:error, :invalid_token}

  # Whether the provider's verdict is final, i.e. retrying the token as an
  # internal HS256 JWT can only fail — and would REPLACE this reason with that
  # verifier's `:signature_error`.
  #
  # That mislabel was the whole reason this exists. Only `:missing_claims` and
  # `:invalid_signature` used to stop here, so an expired Clerk token fell
  # through, failed HS256 (of course — it is RS256), and got logged as
  # `signature_error`. Prod carried 6753 of those from three users, pointing an
  # investigation at key rotation when the tokens were simply expired.
  #
  # Two different reasons land in this list, so don't read it as one rule:
  #
  #   - Claim-level failures and `:invalid_azp` are conclusive because the token
  #     is provably OURS. Joken verifies the SIGNATURE before it validates
  #     claims, so a claim failure means the signature already checked out, and
  #     `:invalid_azp` is only reachable after `verify_and_validate` returned
  #     `{:ok, _}` (ClerkToken.verify_clerk_jwt/1).
  #   - `:missing_claims` and `:invalid_signature` are pre-existing entries kept
  #     for behaviour parity. `:invalid_signature` in particular proves the
  #     OPPOSITE — it says the token was not verifiable — and is here only
  #     because it was here before.
  #
  # `:invalid_token` deliberately stays out: it is the parse-failure rescue,
  # which is exactly the "not a provider token" case the fallback is for.
  #
  # Self-host is unaffected: `Providers.Local.verify_token` and
  # `Accounts.verify_jwt` both call `Engram.Token.verify_and_validate`, so the
  # old fall-through ran the identical verifier twice and returned the identical
  # error. Only the Clerk path's label changes.
  defp conclusive?(reason) when is_list(reason), do: Keyword.has_key?(reason, :claim)
  defp conclusive?(reason), do: reason in [:missing_claims, :invalid_signature, :invalid_azp]

  defp authenticate_internal_jwt(token) do
    case Accounts.verify_jwt(token) do
      {:ok, %{"user_id" => user_id}} when is_binary(user_id) ->
        case Accounts.get_user(user_id) do
          # `:internal_jwt` marker distinguishes device-flow / OAuth /
          # MCP access tokens (all minted via Accounts.generate_jwt) from
          # Clerk-authed web-SPA tokens, so cap plugs can tell programmatic
          # ("external tooling") traffic apart from the user in the app.
          %Accounts.User{} = user -> {:ok, user, :internal_jwt}
          _ -> {:error, :user_not_found}
        end

      {:ok, _claims} ->
        {:error, :missing_claims}

      {:error, reason} ->
        # Preserve Joken's structured failure (e.g. [claim: "exp", ...]) so the
        # auth plug can log *why* the token was rejected.
        {:error, reason}
    end
  end
end
