defmodule Engram.Auth.TokenResolver do
  @moduledoc """
  Shared token→user resolution used by both the Auth plug and UserSocket.

  Handles three auth methods in order:
    1. API key  — `engram_` prefix (always available)
    2. Auth provider JWT — delegates to the configured provider (Clerk RS256 or local HS256)
    3. Internal JWT — HS256 tokens from the device flow (always checked as fallback)

  Returns `{:ok, %User{}}` or `{:error, reason}`.
  """

  alias Engram.Accounts

  @spec resolve(any()) ::
          {:ok, Accounts.User.t()}
          | {:ok, Accounts.User.t(), Accounts.ApiKey.t()}
          | {:ok, Accounts.User.t(), :internal_jwt}
          | {:error, atom() | keyword()}

  def resolve("engram_" <> _ = raw_key) do
    case Accounts.validate_api_key(raw_key) do
      {:ok, user, api_key} -> {:ok, user, api_key}
      {:error, _} = err -> err
    end
  end

  def resolve(token) when is_binary(token) do
    case Engram.Auth.provider().verify_token(token) do
      {:ok, %{external_id: ext_id, email: email}} ->
        Engram.Auth.provider().resolve_user(ext_id, email)

      {:error, :missing_claims} ->
        # Token parsed but lacks required claims — don't try fallback
        {:error, :missing_claims}

      {:error, :invalid_signature} ->
        {:error, :invalid_signature}

      {:error, _} ->
        # Token not recognized by provider — try internal HS256 JWT
        # (device flow access tokens generated by Accounts.generate_jwt/1).
        authenticate_internal_jwt(token)
    end
  end

  def resolve(_), do: {:error, :invalid_token}

  defp authenticate_internal_jwt(token) do
    case Accounts.verify_jwt(token) do
      {:ok, %{"user_id" => user_id}} when is_integer(user_id) ->
        case Accounts.get_user(user_id) do
          # `:internal_jwt` marker distinguishes device-flow / OAuth /
          # MCP access tokens (all minted via Accounts.generate_jwt) from
          # Clerk-authed web-SPA tokens, so cap plugs can tell programmatic
          # ("external tooling") traffic apart from the user in the app.
          %Accounts.User{} = user -> {:ok, user, :internal_jwt}
          _ -> {:error, :user_not_found}
        end

      {:ok, _claims} ->
        {:error, :missing_claims}

      {:error, reason} ->
        # Preserve Joken's structured failure (e.g. [claim: "exp", ...]) so the
        # auth plug can log *why* the token was rejected.
        {:error, reason}
    end
  end
end
