defmodule Engram.Onboarding.Backfill do
  @moduledoc """
  One-shot onboarding backfills for legacy users.

  A plain module rather than a `Mix.Task` — `Mix` is not part of the release
  (see `releases/0` in `mix.exs`), so this is what
  `lib/mix/tasks/engram.backfill_onboarding_actions.ex` wraps, and what release
  rpc calls directly:

      docker exec engram-saas /app/bin/engram rpc 'Engram.Onboarding.Backfill.first_vault_created()'

  Matches `Engram.Links.Backfill` and `Engram.ContentHash.Backfill`.
  """

  import Ecto.Query

  alias Engram.Backfill.TenantScan
  alias Engram.Onboarding.Action
  alias Engram.Repo
  alias Engram.Vaults.Vault

  @doc """
  Insert `first_vault_created` for every user with at least one vault. Returns
  the number of rows inserted.

  Idempotent via the unique index on (user_id, action). The bigserial `id` is
  auto-generated by Postgres and `metadata` defaults to `{}::jsonb`, so both
  are omitted from the insert.
  """
  @spec first_vault_created() :: non_neg_integer()
  def first_vault_created do
    # Not truncated: `Action.inserted_at` is :utc_datetime_usec, which rejects
    # second precision. The raw SQL this replaced cast to timestamptz, so the
    # mismatch only appears once the insert goes through the schema.
    now = DateTime.utc_now()

    # Per-user inside each tenant's RLS context. This was one raw cross-tenant
    # `INSERT ... SELECT FROM vaults`, which reads zero rows on prod under
    # FORCE ROW LEVEL SECURITY and inserts nothing while reporting success
    # (#1349) — the SELECT is policy-bound exactly like any other query.
    #
    # Being tenant-scoped also lets this be a structured Ecto insert rather
    # than raw SQL, so the file no longer needs a `raw_sql_tenant_table_lint`
    # allowlist entry. That entry justified itself as "intentionally
    # cross-tenant", which is precisely the framing
    # docs/context/migrations-force-rls-data-dml.md names as the bug.
    TenantScan.flat_map_users(fn user_id ->
      # Explicit user_id predicate, not ambient RLS alone: on a deployment
      # without the policies (self-host predating them, a restored copy) an
      # unqualified exists? is true for EVERY user as soon as ANY vault exists,
      # permanently marking users as having created one. The replaced SQL
      # carried the correlation; this keeps it.
      if Repo.exists?(from(v in Vault, where: v.user_id == ^user_id)) do
        # Emit the user id per row actually inserted, then count — rather than
        # summing per-user counts. `Enum.sum/1` is specced to return number(),
        # so dialyzer could not prove the non_neg_integer() return; `length/1`
        # it can. It also reads better: the result is "users newly recorded".
        case Repo.insert_all(
               Action,
               [%{user_id: user_id, action: "first_vault_created", inserted_at: now}],
               on_conflict: :nothing,
               conflict_target: [:user_id, :action]
             ) do
          {0, _} -> []
          {_inserted, _} -> [user_id]
        end
      else
        []
      end
    end)
    |> length()
  end
end
