defmodule Engram.Onboarding.Backfill do
  @moduledoc """
  One-shot onboarding backfills for legacy users.

  A plain module rather than a `Mix.Task` — `Mix` is not part of the release
  (see `releases/0` in `mix.exs`), so this is what
  `lib/mix/tasks/engram.backfill_onboarding_actions.ex` wraps, and what release
  rpc calls directly:

      docker exec engram-saas /app/bin/engram rpc 'Engram.Onboarding.Backfill.first_vault_created()'

  Matches `Engram.Links.Backfill` and `Engram.ContentHash.Backfill`.

  Deliberately its own module rather than a function on `Engram.Onboarding`:
  the raw cross-tenant SQL below needs a `raw_sql_tenant_table_lint` allowlist
  entry, and that entry is file-scoped. Parking it on the `Engram.Onboarding`
  context would have exempted every request-path function in that module from
  the RLS-bypass lint too.
  """

  alias Engram.Repo

  @doc """
  Insert `first_vault_created` for every user with at least one vault. Returns
  the number of rows inserted.

  Idempotent via the unique index on (user_id, action). The bigserial `id` is
  auto-generated by Postgres and intentionally omitted from the INSERT column
  list; `metadata` defaults to `{}::jsonb` via the table default.
  """
  @spec first_vault_created() :: non_neg_integer()
  def first_vault_created do
    %{num_rows: count} =
      Repo.query!(
        """
        INSERT INTO onboarding_actions (user_id, action, metadata, inserted_at)
        SELECT DISTINCT v.user_id, 'first_vault_created', '{}'::jsonb, $1::timestamptz
        FROM vaults v
        ON CONFLICT (user_id, action) DO NOTHING
        """,
        [DateTime.utc_now()]
      )

    count
  end
end
